service: ajcwebdev-docker-lambda
frameworkVersion: '2'

provider:
  name: aws
  region: us-west-1
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage:
        path: ./

functions:
  hello:
    image:
      name: appimage